### ISSUE TITLE
Include fitting parameters in md file

### ISSUE THREAD

**Issue by SabineReither** [fmi-faim/eicm#1]
Is it possible to include the following fitting parameters in the output md file
![image](https://user-images.githubusercontent.com/102143576/194537257-835f9db6-83b4-47d8-aea4-eec644a94320.png)

Comment: I don’t think that B (offset) (see png) is background, it is a real offset. In these images we have a homogenies bright signal which should have the same intensity.

**Comment by tibuch** [comment]
Moved the "write-to-md-file" request to [eicm-flows](https://github.com/fmi-faim/prefect-workflows/issues/8).

**Comment by tibuch** [comment]
Fixed with [v0.1.1](https://github.com/fmi-faim/eicm/releases/tag/v0.1.1).
