### ISSUE TITLE
Pixel dimensions in eicm.tif 

### ISSUE THREAD

**Issue by SabineReither** [fmi-faim/eicm#2]
Pixel dimensions in eicm.tif should be either the same as in the input image or no scale, but not 1micron per pixel.
![image](https://user-images.githubusercontent.com/102143576/194561470-db307ce8-7dc5-4cd1-98f0-029e5e79bd6b.png)

**Comment by tibuch** [comment]
Moved to [eicm-flows](https://github.com/fmi-faim/prefect-workflows/issues/7). This package does not save any data :slightly_smiling_face:

**Comment by imagejan** [comment]
@tibuch wrote:
> Moved to https://github.com/fmi-faim/prefect-workflows/issues/7.

Did you know you can *transfer issue*s to other repositories in the GitHub web UI (in the bottom right corner)?

**Comment by tibuch** [comment]
I did not :smile:
