### ISSUE TITLE
Add documentation for preprocessing to README

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/eicm#3]
It would be good to point to `yokogawa.py` in the README as well.

**Comment by tibuch** [comment]
For having it consistent it should appear there, I agree. But I am wondering if we increase the maintenance burden on us by having to update the README for every added function. Maybe we should remove it completely?

**Comment by imagejan** [comment]
I don't have strong feelings about this. You're right, we still have the docstrings that should contain all the necessary information. On the other hand, having a summary of the repo contents in the README might be useful as well.

**Comment by tibuch** [comment]
Moved to https://github.com/fmi-faim/faim-ipa/issues/189.
