### ISSUE TITLE
Add reference computation from tile imaging to preprocessing

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/eicm#4]
@tibuch would it make sense to add preprocessing for tiled acquisitions here in this repository?

I thought about functions to compute a mean image of the (max intensity projected) tiles of a multi-tile dataset (e.g. Metamorph/Visiview `nd/stk`; or multiple `.ome.tif`), to be used with one of the fitting algorithms subsequently. I can add a new file `mean_of_tiles.py` (or maybe `metamorph.py` to be in line with `yokogawa.py`?). What do you think?

**Comment by tibuch** [comment]
Sounds good to me.

**Comment by imagejan** [comment]
Ok, I'll go ahead then.
